registry_name := "registry.localhost"

create:
    k3d registry create {{registry_name}} --port 5000

    k3d cluster create local --registry-use {{registry_name}}

stop:
    k3d cluster stop local

start:
    k3d cluster start local

delete:
    -k3d registry delete k3d-{{registry_name}}
    -k3d cluster delete local
