apiVersion: apps/v1
kind: Deployment
metadata:
  name: xds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xds
  template:
    metadata:
      labels:
        app: xds
    spec:
      serviceAccountName: xds-server-user
      containers:
        - name: xds-server
          image: k3d-registry.localhost:5000/pgn_xds
          ports:
            - name: grpc
              containerPort: 5000
          livenessProbe:
            grpc:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10